name: three_commas
description: 3Commas API wrapper in Dart
version: 0.2.1
homepage: https://github.com/saviobatista/three_commas_api

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  crypto: ^3.0.1
  http: ^0.13.4

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
